
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: bankproject-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel
    working_dir: /var/www


  webserver:
    image: nginx:alpine
    container_name: nginx-server-bankproject
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel


volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
